# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorelib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='composer',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='title',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='voicing',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
    ]
